<?php

session_start();

if(!isset($_SESSION['usuario_online']) OR !($_SESSION['usuario_online'] == true) ){
    header('Location: login.php');


}

require 'controlador_agenda.php';
$meusContatos = buscar($_GET['buscar']);

?>

<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="style.css">
    <meta charset="UTF-8">
    <title>Agendinha</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
</head>
<body>

<div class="social">





    <img src="<?php echo $_SESSION['usuario_link']; ?>" alt="" width="200" height="200">



    <h3>Bem vindo adorável <?=  $_SESSION['usuario_nome']; ?>!</h3>
</div>



<div class="container" style="margin-top: 30px;">

    <h3>MY SWEET CONTACT SCHEDULE :D</h3> 
    <br>
    <br/>



    <!-- CADASTRO-->
    <div class="row">
        <div class="col-md-12">
            <form class="form-inline" method="post" action="controlador_agenda.php?acao=cadastrar">

                <!--nome-->
                <div class="form-group">
                    <label for="nome">Nome</label>
                    <input name="nome" type="text" class="form-control" id="nome">
                </div>

                <!--email-->
                <div class="form-group">
                    <label for="email">Email</label>
                    <input name="email" type="email" class="form-control" id="email">
                </div>

                <!--telefone-->
                <div class="form-group">
                    <label for="telefone">Telefone</label>
                    <input name="telefone" type="text" class="form-control" id="telefone">
                </div>


                <button type="submit" class="btn btn-default">Cadastrar</button> <br><br>


            </form>
        </div>
    </div>

    <!--Buscar-->
    <div class="fa fa-search">
        <form class="form-inline" method="get" action="">

            <label for="buscar">Buscar</label>
            <input name="buscar" type="text" class="form-control" id="buscar">

            <button type="submit" class="btn btn-default">Buscar</button>

        </form>
    </div>


    <br />

    <!--CONTATOS-->
    <div class="row">
        <div class="col-md-12">

            <!-- Conteúdo -->
            <table class="table">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Nome</th>
                    <th>Email</th>
                    <th>Telefone</th>
                    <th>Acoes</th>
                </tr>
                </thead>
                <tbody>
                <!-- repetir -->
                <?php foreach ($meusContatos as $contato): ?>
                    <tr>
                        <td><?= $contato['id'] ?></td>
                        <td><?= $contato['nome'] ?></td>
                        <td><?= $contato['email'] ?></td>
                        <td><?= $contato['telefone'] ?></td>
                        <td>
                            <a href="controlador_agenda.php?acao=excluir&id=<?= $contato['id'] ?>"> Excluir </a> <!--Excluir-->
                            <a href="editar.php?id=<?= $contato['id'] ?>">Editar</a>
                        </td>

                    </tr>
                <?php endforeach; ?>

                </tbody>
            </table>
        </div>
    </div>
</div>

<div class="logout">
<a href="verifica_usuario.php?acao=sair">Sair</a>

</div>

</body>
</html>